web:
  image: jiwhiz/spring-boot-docker-mysql
  links:
    - database
  ports:
    - "8080:8080"

database:
  image: mysql:latest
  volumes:
    - /opt/mysql:/var/lib/mysql:rw
  env_file: extras/docker-compose/compose.env
