web:
  build: .
  links:
    - mysql
  ports:
    - "8080:8080"

database:
  image: mariadb
  volumes:
    - /opt/mysql:/var/lib/mysql:rw
    - extras/docker-compose/my.cnf:/etc/mysql/my.cnf:ro
  env_file: extras/docker-compose/compose.env

cache:
  image: redis

frontend:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - extras/docker-compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
    - extras/docker-compose/nginx_media.conf:/etc/nginx/conf.d/media.conf:ro
    - extras/docker-compose/ssl-certs:/ssl/:ro
  volumes_from:
    - static
    - middleware
  links:
    - middleware